version: "3.9"
services: 
  api:
    container_name: backend_ngcash
    build: ./api
    working_dir: /app-backend
    volumes:
      - ./api:/app-backend
    depends_on:
      - db
    command: npm run dev
    restart: 'unless-stopped'
    environment:
      - JWT_SECRET=secret_key
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_DATABASE=ngcash_db
      - DB_PORT=5432
    ports:
      - 3001:3001
  db: 
    container_name: db_ngcash
    image: postgres:10.17
    restart: 'unless-stopped'
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=ngcash_db 
    ports:
      - 5432:5432
   