version: "3.9"
services: 
  api:
    container_name: backEnd_ngCash
    build: ./api
    working_dir: /app-backend
    volumes:
      - ./api:/app-backend
    depends_on:
      ngcash_db:
        condition: service_healthy
    restart: 'unless-stopped'
    environment:
      - JWT_SECRET=secret_key
      - APP_PORT=3001
      - MYSQL_HOST=login_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
    ports:
      - 3001:3001
  ngcash_db: 
    container_name: database_ngCash
    image: postgres:10.17
    restart: 'unless-stopped'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost'] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=123456
    - POSTGRES_DB=databaseNgCash
    ports:
      - 5432:5432
   